name: Download Godot source code
description: Download and extract the Godot source code for use in compiling
inputs:
  version:
    description: Version of Godot source code to download
    default: "3.5-stable"
  sg-physics-2d-version:
    description: Commit hash from SGPhysics2D main branch to checkout
    default: "a40cdc1cc8bc8a8989ea05f08e877f1ae4de48f0"
runs:
  using: "composite"
  steps:
    - name: Download and extract Godot
      shell: bash
      run: |
        curl -fLO https://github.com/godotengine/godot/archive/${{ inputs.version }}.tar.gz
        tar -xvzf ${{ inputs.version }}.tar.gz --strip-components 1 --exclude=".github"

    - name: Download sg-physics
      shell: bash
      run: |
        git clone https://gitlab.com/snopek-games/sg-physics-2d
        cd sg-physics-2d
        git reset --hard ${{ inputs.sg-physics-2d-version }}

    - name: Move sg-physics-2d to modules folder
      shell: bash
      run: mv sg-physics-2d/godot/modules/sg_physics_2d modules